pc_ip: valid-pc-ip
# Specify a user with permission to make API calls.
pc_credential: pc_user # credential reference from "vaults" in global.yml file

authorization_policies:
  - display_name: String
    description: String
    role: String #Valid Role
    #entities:
    ##  full_access: 
    #    future_access: true
    identities:
      users:
        LOCAL:
          #- admin
          - username
        LDAP:
          - username
      user_groups:
        - group_type: LDAP
          idp: NVD #Valid IDP
          name: user group name
