pc_ip: valid-pc-ip
# Specify a user with permission to make API calls.
pc_credential: pc_user # credential reference from "vaults" in global.yml file

iam_keys:
  - user:
      username: existing username
      user_type: LDAP/LOCAL/SAML/etc
    name: test_iam_key
    description: test_iam_key
    key_type: OBJECT_KEY/API_KEY