pc_ip: valid-pc-ip
# Specify a user with permission to make API calls.
pc_credential: pc_user # credential reference from "vaults" in global.yml file

local_users: #For local users
  - first_name: Sting
    last_name: String
    email: String
    username: String
    password: String

users: #For LDAP/SAML users
  - username: username@ad_domain
    user_type: LDAP
    idp: valid-IP-name #eg. NVD, Okta, AAD